### PR TITLE
Ordered each

### LINKED ISSUE #17: Bin assignment is broken on Firefox

### PR DESCRIPTION
**Pull request by mycrobe**
Fix #17 by explicitly ordering `genomes.each` and `genome.eachRegion`

### CODE REVIEW

File: src/genomes.js [hunk 1]
```diff
@@ -19,15 +20,18 @@ Genomes.prototype.binCount = function() {
 };
 
 Genomes.prototype.each = function(iteratee) {
-  _.forOwn(this._genomes, iteratee, this);
+  _.forEach(this._genomesArray, function(region) {
+    iteratee(region, region.name);
```
Comment (mycrobe) [inline src/genomes.js:24]: Maintain method signature from original implementation
